version: '3.1'
services:
  mongo:
    image: mongo
    restart: 'no'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"

#  mongo-express:
#    image: mongo-express
#    restart: 'no'
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order-service
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
  rabbitmq:
    image: rabbitmq
    restart: 'no'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
  keyclock:
    image: bitnami/keycloak
    depends_on:
      - postgresql
    restart: "no"
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOCK_MANAGEMENT_USER=manager
      - KEYCLOCK_MANAGEMENT_PASSWORD=manager
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=bn_keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
  postgresql:
    image: docker.io/bitnami/postgresql:11
    restart: "no"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"
  vault:
    image: vault
    restart: 'no'
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: vault_dev_token
    ports:
      - "8200:8200"
    deploy:
      resources:
        limits:
          memory: "512M"
          cpus: "1"

  zipkin:
    image: openzipkin/zipkin
    restart: "no"
    ports:
      - "9411:9411"
    deploy:
      resources:
        limits:
          memory: "100M"
          cpus: "0.1"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: 'no'
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    deploy:
      resources:
        limits:
          memory: "1024M"
          cpus: "1"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.1
    restart: 'no'
    volumes:
      - "./logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    ports:
      - "5000:5000"
#    command:
#      - "-f /usr/share/logstash/config/logstash.conf"
    deploy:
      resources:
        limits:
          memory: "1024M"
          cpus: "1"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    restart: 'no'
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    deploy:
      resources:
        limits:
          memory: "1024M"
          cpus: "1"


volumes:
  vault_volume: